version: '3'
services:

  myfinance-postgres:
    image: "postgres:9.6-alpine"
    container_name: myfinance-postgres
    volumes:
      - myfinance-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB:myfinance
      - POSTGRES_USER:myfinance
      - POSTGRES_PASSWORD:myfinance

  myfinance-api:
    build: 
      context: ./back
      dockerfile: Dockerfile.dev
    container_name: myfinance-api
    environment:
      - DB_SERVER=myfinance-postgres
    ports:
      - 3333:8080
    links:
      - myfinance-postgres

  myfinance-front:
    build: ./front
    container_name: myfinance-front
    ports:
      - 3000:80
    links:
      - myfinance-api

volumes:
  myfinance-data: